show variables like 'char%';
set `character_set_client` = utf8;
set `character_set_connection` = utf8;
set `character_set_database` = utf8;
set `character_set_results` = utf8;
set `character_set_server` = utf8;
use mysql;
update  user set host = '%' where user= 'root';
select host, user from user;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '123' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '123' WITH GRANT OPTION;
FLUSH PRIVILEGES;
FLUSH PRIVILEGES;
